import type { Paper } from './types'

const DEMO_USER_ID = 'demo-user-001'
const DEMO_USERNAME = 'researcher'

export const DEMO_PAPERS: Paper[] = [
  {
    id: 'demo-001',
    user_id: DEMO_USER_ID,
    title: 'Deep Learning-Based Semantic Segmentation for Urban Remote Sensing Images',
    title_zh: '基于深度学习的城市遥感图像语义分割方法',
    journal: 'Remote Sensing of Environment',
    status: 'accepted',
    lang: 'en',
    quartile_jcr: 'Q1',
    quartile_cas: '一区',
    quartile_new: 'T1',
    quartile_cust: 'Top',
    quartile_zh: null,
    authors: [DEMO_USERNAME, 'Zhang Wei', 'Li Ming', 'Prof. Wang'],
    submitted_date: '2025-03-15',
    resolve_date: '2025-08-20',
    deadline: null,
    tracking_url: null,
    timeline: null,
    notes: '审稿周期较长，两轮修改后接收',
    prev_id: null,
    files: [{ n: 'manuscript_v3.pdf', p: 'local://manuscript_v3.pdf' }],
    created_at: '2025-03-15T08:00:00Z',
    updated_at: '2025-08-20T12:00:00Z',
  },
  {
    id: 'demo-002',
    user_id: DEMO_USER_ID,
    title: 'Attention-Enhanced Transformer for Multi-Modal Sentiment Analysis',
    title_zh: '注意力增强Transformer的多模态情感分析',
    journal: 'IEEE Transactions on Affective Computing',
    status: 'under_review',
    lang: 'en',
    quartile_jcr: 'Q1',
    quartile_cas: '一区',
    quartile_new: null,
    quartile_cust: 'Top',
    quartile_zh: null,
    authors: ['Zhang Wei', DEMO_USERNAME, 'Chen Li'],
    submitted_date: '2025-11-02',
    resolve_date: null,
    deadline: null,
    tracking_url: 'https://mc.manuscriptcentral.com/taffc',
    timeline: null,
    notes: '二审中，审稿人要求补充实验',
    prev_id: null,
    files: [],
    created_at: '2025-11-02T10:00:00Z',
    updated_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'demo-003',
    user_id: DEMO_USER_ID,
    title: 'Graph Neural Networks for Protein-Protein Interaction Prediction',
    title_zh: '图神经网络在蛋白质相互作用预测中的应用',
    journal: 'Bioinformatics',
    status: 'revision',
    lang: 'en',
    quartile_jcr: 'Q2',
    quartile_cas: '二区',
    quartile_new: null,
    quartile_cust: 'A',
    quartile_zh: null,
    authors: [DEMO_USERNAME, 'Li Ming'],
    submitted_date: '2025-09-10',
    resolve_date: null,
    deadline: '2026-07-15',
    tracking_url: null,
    timeline: null,
    notes: 'Major revision — 需要补充消融实验和对比实验',
    prev_id: null,
    files: [{ n: 'review_comments.pdf', p: 'local://review_comments.pdf' }],
    created_at: '2025-09-10T14:00:00Z',
    updated_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'demo-004',
    user_id: DEMO_USER_ID,
    title: 'Federated Learning with Differential Privacy for Healthcare Data',
    title_zh: '面向医疗数据的差分隐私联邦学习方法',
    journal: 'Journal of Biomedical Informatics',
    status: 'rejected',
    lang: 'en',
    quartile_jcr: 'Q2',
    quartile_cas: '三区',
    quartile_new: null,
    quartile_cust: 'B',
    quartile_zh: null,
    authors: ['Chen Li', DEMO_USERNAME, 'Prof. Wang'],
    submitted_date: '2025-06-20',
    resolve_date: '2025-10-05',
    deadline: null,
    tracking_url: null,
    timeline: null,
    notes: '审稿人认为创新点不足，考虑转投其他期刊',
    prev_id: null,
    files: [],
    created_at: '2025-06-20T09:00:00Z',
    updated_at: '2025-10-05T16:00:00Z',
  },
  {
    id: 'demo-005',
    user_id: DEMO_USER_ID,
    title: '基于大语言模型的中文学术文本自动摘要研究',
    title_zh: '基于大语言模型的中文学术文本自动摘要研究',
    journal: '计算机学报',
    status: 'accepted',
    lang: 'zh',
    quartile_jcr: null,
    quartile_cas: null,
    quartile_new: null,
    quartile_cust: null,
    quartile_zh: ['北大核心', 'CSCD', 'EI'],
    authors: [DEMO_USERNAME, 'Zhang Wei'],
    submitted_date: '2025-04-08',
    resolve_date: '2025-12-15',
    deadline: null,
    tracking_url: null,
    timeline: null,
    notes: '中文期刊审稿周期较长',
    prev_id: null,
    files: [{ n: 'final_version.pdf', p: 'local://final_version.pdf' }],
    created_at: '2025-04-08T11:00:00Z',
    updated_at: '2025-12-15T10:00:00Z',
  },
  {
    id: 'demo-006',
    user_id: DEMO_USER_ID,
    title: 'Lightweight Neural Architecture Search for Edge Devices',
    title_zh: '面向边缘设备的轻量级神经架构搜索',
    journal: 'Neural Computing and Applications',
    status: 'preparing',
    lang: 'en',
    quartile_jcr: 'Q2',
    quartile_cas: '二区',
    quartile_new: null,
    quartile_cust: 'A',
    quartile_zh: null,
    authors: [DEMO_USERNAME, 'Li Ming', 'Chen Li'],
    submitted_date: null,
    resolve_date: null,
    deadline: null,
    tracking_url: null,
    timeline: null,
    notes: '正在完善实验部分，预计下月投稿',
    prev_id: null,
    files: [],
    created_at: '2026-05-01T08:00:00Z',
    updated_at: '2026-06-20T15:00:00Z',
  },
  {
    id: 'demo-007',
    user_id: DEMO_USER_ID,
    title: 'Contrastive Learning for Cross-Domain Object Detection',
    title_zh: '对比学习在跨域目标检测中的应用',
    journal: 'Computer Vision and Image Understanding',
    status: 'submitted',
    lang: 'en',
    quartile_jcr: 'Q2',
    quartile_cas: '二区',
    quartile_new: null,
    quartile_cust: 'A',
    quartile_zh: null,
    authors: ['Zhang Wei', DEMO_USERNAME],
    submitted_date: '2026-06-10',
    resolve_date: null,
    deadline: null,
    tracking_url: null,
    timeline: null,
    notes: '刚投稿，等待编辑分配',
    prev_id: null,
    files: [{ n: 'submission.pdf', p: 'local://submission.pdf' }],
    created_at: '2026-06-10T09:00:00Z',
    updated_at: '2026-06-10T09:00:00Z',
  },
]

export const DEMO_PROFILE = {
  id: DEMO_USER_ID,
  username: DEMO_USERNAME,
  display_name: 'Demo Researcher',
  avatar_url: null,
  created_at: '2025-01-01T00:00:00Z',
  is_admin: false,
}
